# themes configurations
import = [
  # "themes/catppuccin-latte.toml",
  # "themes/catppuccin-frappe.toml",
  # "themes/catppuccin-macchiato.toml",
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[shell]
program = "/usr/bin/zsh"
args    = ["-c", "tmux attach || tmux new -s default"]

[env]
TERM = "tmux-256color"

[font]
normal      = { family = "JetBrainsMono Nerd Font Mono"}
italic      = { family = "JetBrainsMono Nerd Font Mono"}
bold        = { family = "JetBrainsMono Nerd Font Mono"}
bold_italic = { family = "JetBrainsMono Nerd Font Mono"}
size        = 10

[window]
decorations  = "None"
startup_mode = "Maximized"
blur         = true
opacity      = 1

[keyboard]
bindings = [
{ key = "[", mods = "Control", action = "ToggleViMode" },
]

