export EDITOR='nvim'

# aliases
alias pbcopy="xclip -sel clip"
alias open="xdg-open ."
alias upd="sudo apt-get update"
alias upg="sudo apt-get upgrade"
alias ins="sudo apt-get install"
alias ar="sudo apt autoremove"
alias start="sudo systemctl start $1"
alias stop="sudo systemctl stop $1"
alias status="sudo systemctl status $1"
alias restart="sudo systemctl restart $1"
alias enable="sudo systemctl enable $1"
alias disable="sudo systemctl disable $1"
alias reload="source ~/.zshrc"
alias vim="nvim"
alias vi="nvim"

# virtualenv settings
export PATH="$HOME/.local/bin:$PATH"
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"
source $HOME/.local/bin/virtualenvwrapper.sh
