export EDITOR='nvim'

# alias
alias pbcopy="xclip -sel clip"
alias open="nautilus . & disown"
alias vim="nvim"

# virtualenv settings
export PATH="$HOME/.local/bin:$PATH"
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"
source $HOME/.local/bin/virtualenvwrapper.sh
