# editor
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='nvim'
else
    export EDITOR='nvim'
fi


# alias
alias cdbfk="cd /media/nb/BackupFiles"
alias pbcopy="xclip -sel clip"
alias open="nautilus . & disown"
alias vconfig="vim ~/dotfiles/init.vim"
alias zconfig="vim ~/dotfiles/.zshrc"
alias tconfig="vim ~/dotfiles/.tmux.conf"
alias bconfig="vim ~/dotfiles/.bashrc"
alias ls="colorls $*"
alias vim="nvim"

# python virtualenv settings 
export PATH=/home/nb/.local/bin:$PATH
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=/media/nb/BackupFiles/Projects
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /home/nb/.local/bin/virtualenvwrapper.sh

# go path
export PATH=$PATH:/usr/local/go/bin


# tmux fix for virtualenv
if [ -n "$VIRTUAL_ENV" ]; then
     source $VIRTUAL_ENV/bin/activate;
fi


# starship prompt in shell
export STARSHIP_CONFIG=~/.starship.toml

if [ ! $0 = bash ]; then
    eval "$(starship init /usr/bin/zsh)";
else
    eval "$(starship init $0)";
fi

