# Don't print a new line at the start of the prompt
add_newline = true

[character]
disabled = false
symbol = "➜ "


[username]
disabled = false
show_always = true


[hostname]
ssh_only = false
disabled = false


[directory]
disabled = false
truncation_length = 3
