# fix terminal colours and tell Tmux that outside terminal supports true colour
set -g default-terminal "screen-256color" # colors!  set -ga terminal-overrides ",xterm-256color*:Tc"

# tmux package manager Prefix+I or Prefix+U
set -g @plugin 'tmux-plugins/tpm'

# default tmux settings
set -g @plugin 'tmux-plugins/tmux-sensible'

# copying contents inside tmux
set -g @plugin 'tmux-plugins/tmux-yank'

# regex search highlighting
set -g @plugin 'tmux-plugins/tmux-copycat'

# open highlighted selection
set -g @plugin 'tmux-plugins/tmux-open'

# show windows name in middle of statusline
set -g @plugin 'jimeh/tmux-themepack'

# show fancy statusline with dracula accent
set -g @plugin 'sei40kr/tmux-airline-dracula'

# set status bar in top
set-option -g status-position top

# start windows numbering at 1
set -g base-index 1

# make pane numbering consistent with windows
set -g pane-base-index 1

# rename window to reflect current program
set -g automatic-rename on

# change Tmux prefix from C-b to C-a
unbind C-b
set -g prefix C-a

# vim shortcuts to navigate panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# initialize tpm
run -b '~/.tmux/plugins/tpm/tpm'

