# fix terminal colours and tell Tmux that outside terminal supports true colour
set -g default-terminal "screen-256color" 

# Plugin Start (Prefix+I or Prefix+U)
set -g @plugin 'tmux-plugins/tpm'           # tmux plugin manager
set -g @plugin 'tmux-plugins/tmux-sensible'   # default tmux settings
set -g @plugin 'jimeh/tmux-themepack'         # show windows name in middle of statusline
# Plugin End

# status bar at top, numbering windows from 1 instead of 0, automatic window title
set-option -g status-position top
set -g base-index 1
set -g automatic-rename on
set -g @themepack 'powerline/block/cyan'

# change Tmux prefix from C-b to C-a
unbind C-b
set -g prefix C-a

# vim shortcuts to navigate panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# initialize tpm
run -b '~/.tmux/plugins/tpm/tpm'

