# Configuration file for libinput-gestures.

gesture swipe up	    xdotool key ctrl+super+Up
gesture swipe down	    xdotool key ctrl+super+Down


gesture swipe left	    xdotool key super+q
gesture swipe right	    xdotool key super+m


# GNOME SHELL open/close overview (works for GNOME on Xorg only)
gesture pinch in	xdotool key super+s
gesture pinch out	xdotool key super+s

swipe_threshold 0
timeout 1.5
