### List of tmux plugins powered by tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'dracula/tmux'  

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

### Resurrect last saved tmux session on starting tmux
#set -g @continuum-boot 'on'
#set -g @continuum-boot-options 'alacritty'
set -g @continuum-restore 'on'
set-option -sa terminal-overrides ',xterm-256color:RGB'

### Start windows and panes with index 1, not 0
set -g base-index 1
setw -g pane-base-index 1

### Show status bar at top, not bottom
set-option -g status-position top

### Dracula tmux setup
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-show-battery false
set -g @dracula-cpu-usage true
set -g @dracula-ram-usage true
set -g @dracula-show-fahrenheit false
set -g mouse on

## Fix patched and recommended font for powerlevel10k
set -g default-terminal "screen-256color"

### Fixes escape delay in vim-tmux session.
set -sg escape-time 0

### Use <prefix>u to uninstall tpm plugins not listed on plugin list
### default key <prefix> alt-u doesn't work on mac, because alt is used as modifier in mac
set -g @tpm-clean 'u'

 
### if run as "tmux attach", create a session if one does not already exist
new-session -A -s "default"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
################################################################################

